/**
 * Named English copy used by Electron E2E locators. The strings mirror the
 * English dictionary in `apps/desktop/src/renderer/i18n.ts`; when the
 * dictionary changes, this fixture must change with it. Templates are exposed
 * as small helpers so specs never inline user-visible text.
 */
export const APP_TEXT = {
  account: {
    deposit: 'Deposit',
    validationFailed: 'Check the account details.',
    onboardingCreate: 'Create account',
    onboardingTitle: 'Create an account',
    withdrawal: 'Withdrawal',
  },
  accounts: { tab: 'Accounts' },
  action: {
    add: 'Add',
    apply: 'Apply',
    cancel: 'Cancel',
    close: 'Close',
    create: 'Create',
    delete: 'Delete',
    deleteSelected: 'Delete selected',
    edit: 'Edit',
    redo: 'Redo',
    reset: 'Reset',
    restore: 'Restore',
    retry: 'Retry',
    save: 'Save',
    undo: 'Undo',
  },
  asset: {
    createConfirmation: (symbol: string) => `Create new asset ${symbol}?`,
    createTitle: 'New asset',
  },
  assets: { tab: 'Assets' },
  catalog: {
    deleteConfirmation: (count: number) =>
      `Delete the selected entries (${count})? Entries with linked data are archived; the rest are deleted permanently.`,
    bulkProgress: (completed: number, total: number) =>
      `Completed ${completed} of ${total}. Retry the remaining ones?`,
  },
  error: {
    insufficientBalance: 'Withdrawal exceeds the available account balance.',
    vaultAlreadyInitialized: 'Choose an empty folder.',
    vaultInvalid: 'This folder is not a valid vault.',
  },
  field: {
    account: 'Account',
    accountOpening: 'Opening balance',
    asset: 'Asset',
    assetType: 'Asset type',
    category: 'Category',
    entryPrice: 'Entry price',
    identifier: 'Identifier',
    language: 'Language',
    result: 'Result',
    status: 'Status',
    tag: 'Tags',
    tagColor: 'Colour',
    tagDescription: 'Comment',
    tagTradeCount: 'Trades',
    theme: 'Theme',
    unit: 'Unit',
  },
  journal: { empty: 'No trades recorded yet.' },
  instrumentCategory: { crypto: 'Crypto', equities: 'Equities' },
  language: { russian: 'Russian' },
  navigation: {
    catalog: 'Accounts, assets & tags',
    settings: 'Settings',
    /** The Russian dictionary label; used to prove the language switch applied. */
    settingsRussian: 'Настройки',
    statistics: 'Statistics',
    trades: 'Trades',
  },
  onboarding: {
    create: 'Create vault',
    open: 'Open vault',
    title: 'Your offline trading journal',
  },
  settings: {
    backup: 'Create backup',
    backupSuccess: 'Backup created and verified.',
    restore: 'Restore to new folder',
    restoreSuccess: 'Restored vault is ready. Open it using Change vault.',
    vaultChange: 'Change vault',
    vaultCheck: 'Check vault',
    vaultValid: 'The vault folder is valid.',
  },
  statistics: {
    accounts: 'Accounts',
    assets: 'Assets',
    categories: 'Categories',
    directions: 'Directions',
    period: 'Period',
    totalTrades: 'Trades',
  },
  status: { active: 'Active', archived: 'Archived' },
  table: {
    deleteEntriesTitle: 'Delete entries',
    entryType: 'Entry type',
    filterColumn: (column: string) => `Filter ${column}`,
    filterIdentifier: 'Filter identifier and notes',
    filterMaximum: 'Maximum',
    filterMinimum: 'Minimum',
    filterRangeInvalid: 'Minimum must not exceed maximum.',
    filterResetAll: 'Reset all filters',
    filterSearch: 'Search values',
    layout: 'Table view',
    scrollRegion: 'Scrollable table',
    selectRow: 'Select trade',
  },
  tag: {
    addPlaceholder: 'Add tags',
    color: { rose: 'Rose' },
    createOption: (name: string) => `Create tag "${name}"`,
    editTitle: 'Edit tag',
    filterUntagged: 'Without tags',
    namePlaceholder: 'Tag name',
    pickerLabel: 'Tags',
  },
  tags: { tab: 'Tags' },
  theme: { auto: 'Auto', dark: 'Dark', light: 'Light' },
  trade: {
    addExit: 'Add exit',
    conversionPreview: (value: string, unit: string) => `= ${value} ${unit}`,
    details: 'Trade details',
    directionLong: 'Long',
    directionShort: 'Short',
    entryNote: 'Entry note',
    executionSection: 'Execution',
    oneRiskUsd: '1R, USD',
    removeExit: 'Remove exit',
    reviewNote: 'Post-trade review',
    reviewReviewed: 'Reviewed',
    reviewStatus: 'Review status',
    riskMissingTitle: 'Set the 1R value',
    unitPercent: '%',
    unitR: 'R',
    withDetails: 'With details',
  },
  validation: { mustBePositive: 'Value must be greater than zero.' },
} as const;
