import type { RendererGateway } from './renderer-gateway';

/**
 * Renderer adapter over the typed preload API. Every method is part of the
 * preload contract, so the adapter forwards directly and never fabricates a
 * successful empty result: a stale or missing preload surface must fail loudly
 * instead of silently presenting empty catalogues or a missing vault.
 */
export const createElectronRendererGateway = (): RendererGateway => ({
  getDiagnostics: () => window.tjournal.diagnostics.getStatus(),
  subscribeToChanges: (listener) => window.tjournal.changes.subscribe(listener),
  createVault: () => window.tjournal.vault.create(),
  createVaultBackup: () => window.tjournal.vault.backup(),
  listVaultBackups: (beforeId) => window.tjournal.vault.backups(beforeId),
  verifyVaultBackup: (id) => window.tjournal.vault.verifyBackup(id),
  restoreVaultBackup: (id) => window.tjournal.vault.restoreBackup(id),
  openVault: () => window.tjournal.vault.open(),
  revealVaultFolder: () => window.tjournal.vault.revealInFolder(),
  validateVault: () => window.tjournal.vault.validate(),
  createInstrument: (input) => window.tjournal.instruments.create(input),
  updateInstrument: (input) => window.tjournal.instruments.update(input),
  deleteInstrument: (id) => window.tjournal.instruments.delete(id),
  restoreInstrument: (id) => window.tjournal.instruments.restore(id),
  createAccount: (input) => window.tjournal.accounts.create(input),
  listAccounts: () => window.tjournal.accounts.list(),
  updateAccount: (input) => window.tjournal.accounts.update(input),
  deleteAccount: (id) => window.tjournal.accounts.delete(id),
  restoreAccount: (id) => window.tjournal.accounts.restore(id),
  listAccountDefaults: (id) => window.tjournal.accounts.defaults(id),
  createCashMovement: (input) => window.tjournal.cashMovements.create(input),
  deleteCashMovement: (id) => window.tjournal.cashMovements.delete(id),
  listCashMovements: () => window.tjournal.cashMovements.list(),
  updateCashMovement: (input) => window.tjournal.cashMovements.update(input),
  createTrade: (input) => window.tjournal.trades.create(input),
  deleteTrade: (id) => window.tjournal.trades.delete(id),
  deleteTrades: (ids) => window.tjournal.trades.deleteMany(ids),
  getHistory: () => window.tjournal.history.getState(),
  getInstrumentProfile: (instrumentId) => window.tjournal.instrumentProfiles.get(instrumentId),
  getSettings: () => window.tjournal.settings.get(),
  getTradePreferences: () => window.tjournal.tradePreferences.get(),
  getTrade: (id) => window.tjournal.trades.get(id),
  getTradeSummary: (input) => window.tjournal.analytics.summary(input),
  getAnalyticsReport: (input) => window.tjournal.analytics.report(input),
  listInstruments: () => window.tjournal.instruments.list(),
  listTags: () => window.tjournal.tags.list(),
  getTagTradeCounts: () => window.tjournal.tags.counts(),
  createTag: (input) => window.tjournal.tags.create(input),
  updateTag: (input) => window.tjournal.tags.update(input),
  deleteTags: (ids) => window.tjournal.tags.deleteMany(ids),
  getJournalPage: (input) => window.tjournal.trades.page(input),
  redo: () => window.tjournal.history.redo(),
  undo: () => window.tjournal.history.undo(),
  updateSettings: (input) => window.tjournal.settings.update(input),
  updateInstrumentProfile: (input) => window.tjournal.instrumentProfiles.update(input),
  updateTradePreferences: (input) => window.tjournal.tradePreferences.update(input),
  updateTrade: (input) => window.tjournal.trades.update(input),
});
